//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xitari {

class XitariLibPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="SWIGRegisterExceptionCallbacks_XitariLib")]
    public static extern void SWIGRegisterExceptionCallbacks_XitariLib(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_XitariLib")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_XitariLib(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_XitariLib(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_XitariLib(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(XitariLibPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(XitariLibPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="SWIGRegisterStringCallback_XitariLib")]
    public static extern void SWIGRegisterStringCallback_XitariLib(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_XitariLib(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static XitariLibPINVOKE() {
  }


  protected class SWIGWStringHelper {

    public delegate string SWIGWStringDelegate(global::System.IntPtr message);
    static SWIGWStringDelegate wstringDelegate = new SWIGWStringDelegate(CreateWString);

    [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="SWIGRegisterWStringCallback_XitariLib")]
    public static extern void SWIGRegisterWStringCallback_XitariLib(SWIGWStringDelegate wstringDelegate);

    static string CreateWString([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]global::System.IntPtr cString) {
      return global::System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
    }

    static SWIGWStringHelper() {
      SWIGRegisterWStringCallback_XitariLib(wstringDelegate);
    }
  }

  static protected SWIGWStringHelper swigWStringHelper = new SWIGWStringHelper();


  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Clear")]
  public static extern void IntVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Add")]
  public static extern void IntVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_size")]
  public static extern uint IntVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_capacity")]
  public static extern uint IntVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_reserve")]
  public static extern void IntVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_IntVector__SWIG_0")]
  public static extern global::System.IntPtr new_IntVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_IntVector__SWIG_1")]
  public static extern global::System.IntPtr new_IntVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_IntVector__SWIG_2")]
  public static extern global::System.IntPtr new_IntVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_getitemcopy")]
  public static extern int IntVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_getitem")]
  public static extern int IntVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_setitem")]
  public static extern void IntVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_AddRange")]
  public static extern void IntVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_GetRange")]
  public static extern global::System.IntPtr IntVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Insert")]
  public static extern void IntVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_InsertRange")]
  public static extern void IntVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_RemoveAt")]
  public static extern void IntVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_RemoveRange")]
  public static extern void IntVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Repeat")]
  public static extern global::System.IntPtr IntVector_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Reverse__SWIG_0")]
  public static extern void IntVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Reverse__SWIG_1")]
  public static extern void IntVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_SetRange")]
  public static extern void IntVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Contains")]
  public static extern bool IntVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_IndexOf")]
  public static extern int IntVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_LastIndexOf")]
  public static extern int IntVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_IntVector_Remove")]
  public static extern bool IntVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_delete_IntVector")]
  public static extern void delete_IntVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Clear")]
  public static extern void SizeTVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Add")]
  public static extern void SizeTVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_size")]
  public static extern uint SizeTVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_capacity")]
  public static extern uint SizeTVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_reserve")]
  public static extern void SizeTVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_SizeTVector__SWIG_0")]
  public static extern global::System.IntPtr new_SizeTVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_SizeTVector__SWIG_1")]
  public static extern global::System.IntPtr new_SizeTVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_SizeTVector__SWIG_2")]
  public static extern global::System.IntPtr new_SizeTVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_getitemcopy")]
  public static extern uint SizeTVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_getitem")]
  public static extern uint SizeTVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_setitem")]
  public static extern void SizeTVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_AddRange")]
  public static extern void SizeTVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_GetRange")]
  public static extern global::System.IntPtr SizeTVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Insert")]
  public static extern void SizeTVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_InsertRange")]
  public static extern void SizeTVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_RemoveAt")]
  public static extern void SizeTVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_RemoveRange")]
  public static extern void SizeTVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Repeat")]
  public static extern global::System.IntPtr SizeTVector_Repeat(uint jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Reverse__SWIG_0")]
  public static extern void SizeTVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Reverse__SWIG_1")]
  public static extern void SizeTVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_SetRange")]
  public static extern void SizeTVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Contains")]
  public static extern bool SizeTVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_IndexOf")]
  public static extern int SizeTVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_LastIndexOf")]
  public static extern int SizeTVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_SizeTVector_Remove")]
  public static extern bool SizeTVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_delete_SizeTVector")]
  public static extern void delete_SizeTVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Clear")]
  public static extern void DoubleVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Add")]
  public static extern void DoubleVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_size")]
  public static extern uint DoubleVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_capacity")]
  public static extern uint DoubleVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_reserve")]
  public static extern void DoubleVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_DoubleVector__SWIG_0")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_DoubleVector__SWIG_1")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_DoubleVector__SWIG_2")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_getitemcopy")]
  public static extern double DoubleVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_getitem")]
  public static extern double DoubleVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_setitem")]
  public static extern void DoubleVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_AddRange")]
  public static extern void DoubleVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_GetRange")]
  public static extern global::System.IntPtr DoubleVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Insert")]
  public static extern void DoubleVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_InsertRange")]
  public static extern void DoubleVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_RemoveAt")]
  public static extern void DoubleVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_RemoveRange")]
  public static extern void DoubleVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Repeat")]
  public static extern global::System.IntPtr DoubleVector_Repeat(double jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Reverse__SWIG_0")]
  public static extern void DoubleVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Reverse__SWIG_1")]
  public static extern void DoubleVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_SetRange")]
  public static extern void DoubleVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Contains")]
  public static extern bool DoubleVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_IndexOf")]
  public static extern int DoubleVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_LastIndexOf")]
  public static extern int DoubleVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_DoubleVector_Remove")]
  public static extern bool DoubleVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_delete_DoubleVector")]
  public static extern void delete_DoubleVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Clear")]
  public static extern void FloatVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Add")]
  public static extern void FloatVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_size")]
  public static extern uint FloatVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_capacity")]
  public static extern uint FloatVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_reserve")]
  public static extern void FloatVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_FloatVector__SWIG_0")]
  public static extern global::System.IntPtr new_FloatVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_FloatVector__SWIG_1")]
  public static extern global::System.IntPtr new_FloatVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_FloatVector__SWIG_2")]
  public static extern global::System.IntPtr new_FloatVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_getitemcopy")]
  public static extern float FloatVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_getitem")]
  public static extern float FloatVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_setitem")]
  public static extern void FloatVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_AddRange")]
  public static extern void FloatVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_GetRange")]
  public static extern global::System.IntPtr FloatVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Insert")]
  public static extern void FloatVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_InsertRange")]
  public static extern void FloatVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_RemoveAt")]
  public static extern void FloatVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_RemoveRange")]
  public static extern void FloatVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Repeat")]
  public static extern global::System.IntPtr FloatVector_Repeat(float jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Reverse__SWIG_0")]
  public static extern void FloatVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Reverse__SWIG_1")]
  public static extern void FloatVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_SetRange")]
  public static extern void FloatVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Contains")]
  public static extern bool FloatVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_IndexOf")]
  public static extern int FloatVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_LastIndexOf")]
  public static extern int FloatVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_FloatVector_Remove")]
  public static extern bool FloatVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_delete_FloatVector")]
  public static extern void delete_FloatVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Clear")]
  public static extern void BoolVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Add")]
  public static extern void BoolVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_size")]
  public static extern uint BoolVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_capacity")]
  public static extern uint BoolVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_reserve")]
  public static extern void BoolVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_BoolVector__SWIG_0")]
  public static extern global::System.IntPtr new_BoolVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_BoolVector__SWIG_1")]
  public static extern global::System.IntPtr new_BoolVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_BoolVector__SWIG_2")]
  public static extern global::System.IntPtr new_BoolVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_getitemcopy")]
  public static extern bool BoolVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_getitem")]
  public static extern bool BoolVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_setitem")]
  public static extern void BoolVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_AddRange")]
  public static extern void BoolVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_GetRange")]
  public static extern global::System.IntPtr BoolVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Insert")]
  public static extern void BoolVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_InsertRange")]
  public static extern void BoolVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_RemoveAt")]
  public static extern void BoolVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_RemoveRange")]
  public static extern void BoolVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Repeat")]
  public static extern global::System.IntPtr BoolVector_Repeat(bool jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Reverse__SWIG_0")]
  public static extern void BoolVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Reverse__SWIG_1")]
  public static extern void BoolVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_SetRange")]
  public static extern void BoolVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Contains")]
  public static extern bool BoolVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_IndexOf")]
  public static extern int BoolVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_LastIndexOf")]
  public static extern int BoolVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_BoolVector_Remove")]
  public static extern bool BoolVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_delete_BoolVector")]
  public static extern void delete_BoolVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_new_XitariALE")]
  public static extern global::System.IntPtr new_XitariALE(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_fillRgbFromPalette")]
  public static extern void XitariALE_ale_fillRgbFromPalette(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_gc")]
  public static extern void XitariALE_ale_gc(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_act")]
  public static extern double XitariALE_ale_act(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_getScreenWidth")]
  public static extern int XitariALE_ale_getScreenWidth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_getScreenHeight")]
  public static extern int XitariALE_ale_getScreenHeight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_isGameOver")]
  public static extern bool XitariALE_ale_isGameOver(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_resetGame")]
  public static extern void XitariALE_ale_resetGame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_saveState")]
  public static extern void XitariALE_ale_saveState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_loadState")]
  public static extern bool XitariALE_ale_loadState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_fillObs")]
  public static extern void XitariALE_ale_fillObs(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_fillRamObs")]
  public static extern void XitariALE_ale_fillRamObs(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_numLegalActions")]
  public static extern int XitariALE_ale_numLegalActions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_legalActions")]
  public static extern global::System.IntPtr XitariALE_ale_legalActions(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_livesRemained")]
  public static extern int XitariALE_ale_livesRemained(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_getSnapshotLength")]
  public static extern int XitariALE_ale_getSnapshotLength(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_saveSnapshot")]
  public static extern void XitariALE_ale_saveSnapshot(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_XitariALE_ale_restoreSnapshot")]
  public static extern void XitariALE_ale_restoreSnapshot(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("Xitari.Core.CSBinding-0.4.dll", EntryPoint="CSharp_Xitari_delete_XitariALE")]
  public static extern void delete_XitariALE(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
