//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xitari {

public class XitariALE : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XitariALE(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XitariALE obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XitariALE() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XitariLibPINVOKE.delete_XitariALE(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XitariALE(string rom_file) : this(XitariLibPINVOKE.new_XitariALE(rom_file), true) {
  }

  public void ale_fillRgbFromPalette(UCharVector rgb, UCharVector obs, uint rgb_size, uint obs_size) {
    XitariLibPINVOKE.XitariALE_ale_fillRgbFromPalette(swigCPtr, UCharVector.getCPtr(rgb), UCharVector.getCPtr(obs), rgb_size, obs_size);
    if (XitariLibPINVOKE.SWIGPendingException.Pending) throw XitariLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ale_gc() {
    XitariLibPINVOKE.XitariALE_ale_gc(swigCPtr);
  }

  public double ale_act(int action) {
    double ret = XitariLibPINVOKE.XitariALE_ale_act(swigCPtr, action);
    return ret;
  }

  public int ale_getScreenWidth() {
    int ret = XitariLibPINVOKE.XitariALE_ale_getScreenWidth(swigCPtr);
    return ret;
  }

  public int ale_getScreenHeight() {
    int ret = XitariLibPINVOKE.XitariALE_ale_getScreenHeight(swigCPtr);
    return ret;
  }

  public bool ale_isGameOver() {
    bool ret = XitariLibPINVOKE.XitariALE_ale_isGameOver(swigCPtr);
    return ret;
  }

  public void ale_resetGame() {
    XitariLibPINVOKE.XitariALE_ale_resetGame(swigCPtr);
  }

  public void ale_saveState() {
    XitariLibPINVOKE.XitariALE_ale_saveState(swigCPtr);
  }

  public bool ale_loadState() {
    bool ret = XitariLibPINVOKE.XitariALE_ale_loadState(swigCPtr);
    return ret;
  }

  public void ale_getScreenRGB(UCharVector rgb) {
    XitariLibPINVOKE.XitariALE_ale_getScreenRGB(swigCPtr, UCharVector.getCPtr(rgb));
    if (XitariLibPINVOKE.SWIGPendingException.Pending) throw XitariLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public UCharVector ale_getRescaledYChannelScreen() {
    UCharVector ret = new UCharVector(XitariLibPINVOKE.XitariALE_ale_getRescaledYChannelScreen(swigCPtr), true);
    return ret;
  }

  public void ale_fillRgb2yFromPalette(UCharVector y, UCharVector obs, uint y_size, uint obs_size) {
    XitariLibPINVOKE.XitariALE_ale_fillRgb2yFromPalette(swigCPtr, UCharVector.getCPtr(y), UCharVector.getCPtr(obs), y_size, obs_size);
    if (XitariLibPINVOKE.SWIGPendingException.Pending) throw XitariLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public UCharVector ale_resizeBilinearGray(UCharVector y, int w, int h, int w2, int h2) {
    UCharVector ret = new UCharVector(XitariLibPINVOKE.XitariALE_ale_resizeBilinearGray(swigCPtr, UCharVector.getCPtr(y), w, h, w2, h2), true);
    if (XitariLibPINVOKE.SWIGPendingException.Pending) throw XitariLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int ale_numLegalActions() {
    int ret = XitariLibPINVOKE.XitariALE_ale_numLegalActions(swigCPtr);
    return ret;
  }

  public IntVector ale_legalActions(uint actions_size) {
    IntVector ret = new IntVector(XitariLibPINVOKE.XitariALE_ale_legalActions(swigCPtr, actions_size), true);
    return ret;
  }

  public int ale_livesRemained() {
    int ret = XitariLibPINVOKE.XitariALE_ale_livesRemained(swigCPtr);
    return ret;
  }

  public int ale_getSnapshotLength() {
    int ret = XitariLibPINVOKE.XitariALE_ale_getSnapshotLength(swigCPtr);
    return ret;
  }

}

}
